// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LesliesWarehouseAPI.Models
{
    public partial class EditRequest
    {
        public int RequestId { get; set; }
        public int? EmployeeId { get; set; }
        public string RequestDescription { get; set; }
        public string RequestType { get; set; }
        public DateTime? RequestDate { get; set; }

        public virtual Employee Employee { get; set; }
    }
}