// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LesliesWarehouseAPI.Models
{
    public partial class Employee
    {
        public Employee()
        {
            EditRequests = new HashSet<EditRequest>();
            PunchIns = new HashSet<PunchIn>();
            PunchOuts = new HashSet<PunchOut>();
            Titles = new HashSet<Title>();
            Warnings = new HashSet<Warning>();
        }

        public int EmployeeId { get; set; }
        public string EmpName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpStreet { get; set; }
        public string EmpCity { get; set; }
        public string EmpState { get; set; }
        public int? EmpZip { get; set; }
        public DateTime? EmpDob { get; set; }
        public DateTime? EmpHiredOnDate { get; set; }

        public virtual ICollection<EditRequest> EditRequests { get; set; }
        public virtual ICollection<PunchIn> PunchIns { get; set; }
        public virtual ICollection<PunchOut> PunchOuts { get; set; }
        public virtual ICollection<Title> Titles { get; set; }
        public virtual ICollection<Warning> Warnings { get; set; }
    }
}