// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LesliesWarehouseAPI.Models
{
    public partial class PunchIn
    {
        public int PunchInId { get; set; }
        public int? EmployeeId { get; set; }
        public TimeSpan? PunchInTime { get; set; }
        public string PunchInType { get; set; }
        public DateTime? PunchInDate { get; set; }

        public virtual Employee Employee { get; set; }
    }
}