// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LesliesWarehouseAPI.Models
{
    public partial class PunchOut
    {
        public int PunchOutId { get; set; }
        public int? EmployeeId { get; set; }
        public TimeSpan? PunchOutTime { get; set; }
        public string PunchOutType { get; set; }
        public DateTime? PunchOutDate { get; set; }

        public virtual Employee Employee { get; set; }
    }
}