// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LesliesWarehouseAPI.Models
{
    public partial class Title
    {
        public int TitleId { get; set; }
        public int? EmployeeId { get; set; }
        public string TitleName { get; set; }

        public virtual Employee Employee { get; set; }
    }
}