// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LesliesWarehouseAPI.Models
{
    public partial class Warning
    {
        public int WarningId { get; set; }
        public int? EmployeeId { get; set; }
        public string WarningType { get; set; }
        public string WarningDescription { get; set; }
        public DateTime? WarningDate { get; set; }

        public virtual Employee Employee { get; set; }
    }
}